
import { Product } from './types';

export const BLOW_MOULD_TANKS: Product[] = [
    {
        id: 1,
        name: 'SUPER STAR',
        quality: 'Eco',
        technology: 'BLOW',
        layers: 5,
        colors: ['WHITE'],
        capacities: [500, 750, 1000],
        features: ['Plain Lid', 'AntiMicrobial Layer'],
        guarantee: '5 YEARS',
        pricePerLiter: 3.95,
        imageUrl: 'https://picsum.photos/seed/superstar/400/400',
    },
    {
        id: 2,
        name: 'EXCELLENCE',
        quality: 'Premium',
        technology: 'BLOW',
        layers: 5,
        colors: ['P. GOLD'],
        capacities: [500, 750, 1000],
        features: ['Plain Lid', 'AntiMicrobial Layer'],
        guarantee: '10 YEARS*',
        pricePerLiter: 4.50,
        imageUrl: 'https://picsum.photos/seed/excellence/400/400',
        notes: ['10 Years Guarantee product will have Laser Engraving.'],
    },
     {
        id: 17,
        name: 'Super Star 200 & 300 Ltr',
        quality: 'Eco',
        technology: 'BLOW',
        layers: 3,
        colors: ['WHITE'],
        capacities: [200, 300],
        features: ['Plain Lid'],
        guarantee: 'NO GUARANTEE',
        pricePerLiter: 4.25,
        imageUrl: 'https://picsum.photos/seed/superstar200/400/400',
        notes: ['No scheme on 200, 300 ltr Tanks'],
    },
];

export const ROTO_MOULD_TANKS: Product[] = [
    {
        id: 3,
        name: 'SUPER SMART (Inner White) NON - EMBOSSED',
        quality: 'Eco',
        technology: 'ROTO',
        layers: 3,
        colors: ['WHITE', 'BLUE'],
        capacities: [500, 750, 1000, 2000],
        features: ['Plain Lid', 'AntiMicrobial Layer'],
        guarantee: '5 YEARS',
        pricePerLiter: 4.30,
        imageUrl: 'https://picsum.photos/seed/supersmart3/400/400',
    },
    {
        id: 4,
        name: 'SUPER SMART (Inner White) NON - EMBOSSED',
        quality: 'Eco',
        technology: 'ROTO',
        layers: 4,
        colors: ['WHITE', 'BLUE'],
        capacities: [500, 750, 1000, 2000],
        features: ['Plain Lid', 'AntiMicrobial Layer'],
        guarantee: '5 YEARS',
        pricePerLiter: 4.70,
        imageUrl: 'https://picsum.photos/seed/supersmart4/400/400',
    },
    {
        id: 5,
        name: 'SUPER SMART (Inner White) NON - EMBOSSED',
        quality: 'Eco',
        technology: 'ROTO',
        layers: 5,
        colors: ['WHITE', 'BLUE'],
        capacities: [500, 750, 1000, 2000],
        features: ['Plain Lid', 'AntiMicrobial Layer'],
        guarantee: '5 YEARS',
        pricePerLiter: 5.10,
        imageUrl: 'https://picsum.photos/seed/supersmart5/400/400',
    },
    {
        id: 6,
        name: 'REGAL',
        quality: 'Premium',
        technology: 'ROTO',
        layers: 3,
        colors: ['WHITE', 'BLUE'],
        capacities: [500, 750, 1000, 2000],
        features: ['Venting Lid', 'AntiMicrobial Layer'],
        guarantee: '10 YEARS*',
        pricePerLiter: 4.60,
        imageUrl: 'https://picsum.photos/seed/regal/400/400',
        notes: ['10 Years Guarantee product will have Laser Engraving.'],
    },
    {
        id: 7,
        name: 'ROYAL+ (SINGLE PUFF)',
        quality: 'Premium',
        technology: 'ROTO',
        layers: 4,
        colors: ['WHITE'],
        capacities: [500, 750, 1000, 2000],
        features: ['Venting Lid', 'AntiMicrobial Layer'],
        guarantee: '10 YEARS*',
        pricePerLiter: 5.90,
        imageUrl: 'https://picsum.photos/seed/royalplus/400/400',
        notes: ['10 Years Guarantee product will have Laser Engraving.'],
    },
    {
        id: 8,
        name: 'ROYAL++ (DOUBLE PUFF)',
        quality: 'Premium',
        technology: 'ROTO',
        layers: 6,
        colors: ['WHITE'],
        capacities: [500, 750, 1000],
        features: ['Venting Lid', 'AntiMicrobial Layer'],
        guarantee: '10 YEARS*',
        pricePerLiter: 6.90,
        imageUrl: 'https://picsum.photos/seed/royalplusplus/400/400',
        notes: ['10 Years Guarantee product will have Laser Engraving.'],
    },
    {
        id: 9,
        name: 'ROYAL+++ (TRIPLE PUFF)',
        quality: 'Premium',
        technology: 'ROTO',
        layers: 8,
        colors: ['WHITE'],
        capacities: [500, 750, 1000],
        features: ['Venting Lid', 'AntiMicrobial Layer'],
        guarantee: '10 YEARS*',
        pricePerLiter: 7.90,
        imageUrl: 'https://picsum.photos/seed/royalplusplusplus/400/400',
        notes: ['10 Years Guarantee product will have Laser Engraving.'],
    },
    {
        id: 10,
        name: 'REGAL BLACK (NEW STANDARD WEIGHT)',
        quality: 'Improved',
        technology: 'ROTO',
        layers: 2,
        colors: ['BLACK'],
        capacities: [500, 750, 1000, 2000],
        features: ['Plain Lid', 'AntiMicrobial Layer'],
        guarantee: '5 YEARS',
        pricePerLiter: 4.20,
        imageUrl: 'https://picsum.photos/seed/regalblack/400/400',
    },
    {
        id: 11,
        name: 'REGAL 5000',
        quality: 'Premium',
        technology: 'ROTO',
        layers: 3,
        colors: ['WHITE'],
        capacities: [5000],
        features: ['Plain Lid'],
        guarantee: '5 YEARS',
        pricePerLiter: 4.75,
        imageUrl: 'https://picsum.photos/seed/regal5000p/400/400',
        notes: ['No scheme on 5000 ltr Tanks'],
    },
    {
        id: 12,
        name: 'REGAL 5000',
        quality: 'Eco',
        technology: 'ROTO',
        layers: 2,
        colors: ['BLACK'],
        capacities: [5000],
        features: ['Plain Lid'],
        guarantee: '5 YEARS',
        pricePerLiter: 4.30,
        imageUrl: 'https://picsum.photos/seed/regal5000e/400/400',
        notes: ['No scheme on 5000 ltr Tanks'],
    },
    {
        id: 13,
        name: 'REGAL 200 LTR (BLACK)',
        quality: 'Eco',
        technology: 'ROTO',
        layers: 2,
        colors: ['BLACK'],
        capacities: [200],
        features: ['Plain Lid'],
        guarantee: 'NO GUARANTEE',
        pricePerLiter: 5.00,
        imageUrl: 'https://picsum.photos/seed/regal200b/400/400',
        notes: ['No scheme on 200, 300 ltr Tanks'],
    },
    {
        id: 14,
        name: 'REGAL 300 LTR (BLACK)',
        quality: 'Eco',
        technology: 'ROTO',
        layers: 2,
        colors: ['BLACK'],
        capacities: [300],
        features: ['Plain Lid'],
        guarantee: 'NO GUARANTEE',
        pricePerLiter: 4.40,
        imageUrl: 'https://picsum.photos/seed/regal300b/400/400',
        notes: ['No scheme on 200, 300 ltr Tanks'],
    },
    {
        id: 15,
        name: 'REGAL 200 LTR (WHITE)',
        quality: 'Eco',
        technology: 'ROTO',
        layers: 3,
        colors: ['WHITE'],
        capacities: [200],
        features: ['Plain Lid'],
        guarantee: 'NO GUARANTEE',
        pricePerLiter: 5.75,
        imageUrl: 'https://picsum.photos/seed/regal200w/400/400',
        notes: ['No scheme on 200, 300 ltr Tanks'],
    },
    {
        id: 16,
        name: 'REGAL 300 LTR (WHITE)',
        quality: 'Eco',
        technology: 'ROTO',
        layers: 3,
        colors: ['WHITE'],
        capacities: [300],
        features: ['Plain Lid'],
        guarantee: 'NO GUARANTEE',
        pricePerLiter: 5.00,
        imageUrl: 'https://picsum.photos/seed/regal300w/400/400',
        notes: ['No scheme on 200, 300 ltr Tanks'],
    },
    {
        id: 18,
        name: 'COMMERCIAL (As per ISI WEIGHT)',
        quality: 'ISI Weight',
        technology: 'ROTO',
        layers: 2,
        colors: ['BLACK'],
        capacities: [500, 750, 1000, 2000, 5000],
        features: ['Plain Lid'],
        guarantee: '5 YEARS*',
        pricePerLiter: 5.90,
        imageUrl: 'https://picsum.photos/seed/commercial/400/400',
        notes: ['Exchanged tank will have a laser Engraving of guarantee void tanks.'],
    },
];

export const ALL_PRODUCTS: Product[] = [...BLOW_MOULD_TANKS, ...ROTO_MOULD_TANKS];

export const UTTAR_PRADESH_DISTRICTS = [
    "Agra", "Aligarh", "Allahabad", "Ambedkar Nagar", "Amethi", "Amroha", "Auraiya", "Azamgarh", 
    "Baghpat", "Bahraich", "Ballia", "Balrampur", "Banda", "Barabanki", "Bareilly", "Basti", 
    "Bhadohi", "Bijnor", "Budaun", "Bulandshahr", "Chandauli", "Chitrakoot", "Deoria", "Etah", 
    "Etawah", "Faizabad", "Farrukhabad", "Fatehpur", "Firozabad", "Gautam Buddha Nagar", "Ghaziabad", 
    "Ghazipur", "Gonda", "Gorakhpur", "Hamirpur", "Hapur", "Hardoi", "Hathras", "Jalaun", "Jaunpur", 
    "Jhansi", "Kannauj", "Kanpur Dehat", "Kanpur Nagar", "Kasganj", "Kaushambi", "Kheri", "Kushinagar", 
    "Lalitpur", "Lucknow", "Maharajganj", "Mahoba", "Mainpuri", "Mathura", "Mau", "Meerut", "Mirzapur", 
    "Moradabad", "Muzaffarnagar", "Pilibhit", "Pratapgarh", "Raebareli", "Rampur", "Saharanpur", 
    "Sambhal", "Sant Kabir Nagar", "Shahjahanpur", "Shamli", "Shravasti", "Siddharthnagar", "Sitapur", 
    "Sonbhadra", "Sultanpur", "Unnao", "Varanasi"
];
